create table hall(
    id int primary key,
    number_of_seats int check (number_of_seats > 0) not null
);

create table film(
    id int generated by default as identity primary key,
    title varchar(100) not null,
    year_of_release int check (year_of_release > 0) not null,
    age_restriction int check (age_restriction > 0) not null,
    description varchar(1000),
    poster_name varchar(256)
);

create table session(
    id int generated by default as identity primary key,
    hall_id int references hall(id) on delete cascade,
    film_id int references film(id) on delete cascade,
    date_time timestamp not null,
    cost int not null
);

create table user_table(
    id int generated by default as identity primary key
);

create table info(
    id int generated by default as identity primary key,
    date_time timestamp not null,
    ip varchar(100),
    user_id int references user_table(id) on delete cascade
);

create table message(
    id int generated by default as identity primary key,
    message varchar(1000),
    film_id int,
    user_id int
);